//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeMakingMyDecisions.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public System.Guid EntryID { get; set; }
        public string Caption { get; set; }
        public string Submitter { get; set; }
        public string Url { get; set; }
        public string Blog { get; set; }
    }
}
