//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnthonyMemorialFinal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memorial
    {
        public System.Guid SubmitterId { get; set; }
        public string SubmitterName { get; set; }
        public string Picture { get; set; }
        public string Tribute { get; set; }
        public string Story { get; set; }
        public System.DateTime Date { get; set; }
    }
}
