//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryingAgain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public System.Guid PictureId { get; set; }
        public string PictureUrl { get; set; }
        public string DateOfPicture { get; set; }
        public string VisitorName { get; set; }
        public string Caption { get; set; }
        public System.DateTime DatePicturePosted { get; set; }
    }
}
