//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryingAgain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public System.Guid StoryId { get; set; }
        public string Story1 { get; set; }
        public string StoryTeller { get; set; }
        public string Url { get; set; }
        public string DateOfStory { get; set; }
        public System.DateTime DatePosted { get; set; }
    }
}
