//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anthony.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public System.Guid PostId { get; set; }
        public System.Guid GuestId { get; set; }
        public string Url { get; set; }
        public string Comment { get; set; }
        public System.DateTime DatePosted { get; set; }
    }
}
